{{- if and .Values.podDisruptionBudget.enabled (gt (int .Values.replicaCount) 1) }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "l2lb.fullname" . }}
  labels:
    {{- include "l2lb.labels" . | nindent 4 }}
spec:
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  selector:
    matchLabels:
      {{- include "l2lb.selectorLabels" . | nindent 6 }}
{{- end }}
