{{- if not .Values.scaleway.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "l2lb.secretName" . }}
  labels:
    {{- include "l2lb.labels" . | nindent 4 }}
stringData:
  SCW_ACCESS_KEY: {{ required "set scaleway.accessKey (or scaleway.existingSecret)" .Values.scaleway.accessKey | quote }}
  SCW_SECRET_KEY: {{ required "set scaleway.secretKey (or scaleway.existingSecret)" .Values.scaleway.secretKey | quote }}
  SCW_DEFAULT_PROJECT_ID: {{ required "set scaleway.projectID (or scaleway.existingSecret)" .Values.scaleway.projectID | quote }}
  SCW_DEFAULT_REGION: {{ required "set scaleway.region (or scaleway.existingSecret)" .Values.scaleway.region | quote }}
{{- end }}
